stages:
  - quality

lint:prettier:
  image: node:lts-alpine
  stage: quality
  only:
    - merge_requests
  script:
    - apk add git
    - yarn add prettier
    - git fetch --prune
    - yarn prettier --check $(git diff --name-only --diff-filter=ACMTUXB origin/main HEAD | egrep -i
      "[a-z]\.(json|js|tsx)$")
