version: '3.4'

services:
  pcr-mobile-app:
    container_name: pcr-mobile-app
    build:
      context: ./docker
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    env_file:
      - .env
    volumes:
      - ./:/opt/pcr-mobile-app
    healthcheck:
      disable: true